# Generated by Django 4.2.1 on 2023-05-27 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=50)),
                ('temas', models.TextField()),
                ('link', models.URLField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unsa.materia')),
            ],
        ),
    ]
